# golangci-lint configuration

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - exportloopref
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
    
  max-issues-per-linter: 0
  max-same-issues: 0
