version: '3.8'

services:
  nophr:
    # Use pre-built image or build locally
    # image: ghcr.io/sandwichfarm/nophr:latest
    build: .
    image: nophr:latest
    container_name: nophr
    restart: unless-stopped

    ports:
      # Gopher protocol (port 70)
      - "70:70"
      # Gemini protocol (port 1965 with TLS)
      - "1965:1965"
      # Finger protocol (port 79)
      - "79:79"
      # Optional: monitoring/health endpoint
      - "8080:8080"

    volumes:
      # Configuration
      - ./configs/nophr.example.yaml:/etc/nophr/nophr.yaml:ro
      # Data persistence
      - nophr-data:/var/lib/nophr
      # TLS certificates for Gemini (if not using auto-generate)
      - nophr-certs:/etc/nophr/certs:ro
      # Logs (optional)
      - nophr-logs:/var/log/nophr

    environment:
      # IMPORTANT: Never commit your nsec to version control!
      # Set this via .env file or pass at runtime
      - NOPHER_NSEC=${NOPHER_NSEC}
      # Optional: Redis URL if using Redis cache
      - NOPHER_REDIS_URL=${NOPHER_REDIS_URL:-}
      # Optional: Override log level
      - NOPHER_LOG_LEVEL=${NOPHER_LOG_LEVEL:-info}

    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp

    # Health check
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "70"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - nophr-net

  # Optional: Redis cache for better performance
  # Uncomment to enable Redis caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: nophr-redis
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - nophr-net

  # Optional: Caddy reverse proxy for automatic HTTPS
  # Uncomment to enable Caddy for TLS termination
  # caddy:
  #   image: caddy:2-alpine
  #   container_name: nophr-caddy
  #   restart: unless-stopped
  #   ports:
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - ./examples/Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy-data:/data
  #     - caddy-config:/config
  #   networks:
  #     - nophr-net
  #   depends_on:
  #     - nophr

volumes:
  nophr-data:
    driver: local
  nophr-certs:
    driver: local
  nophr-logs:
    driver: local
  # redis-data:
  #   driver: local
  # caddy-data:
  #   driver: local
  # caddy-config:
  #   driver: local

networks:
  nophr-net:
    driver: bridge
