name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v2.1.3, etc.)

permissions:
  contents: write  # Required for creating releases
  packages: write  # Required for Docker images

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for changelog generation

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Setup CI
      run: ./scripts/ci/setup.sh

    - name: Run tests
      run: ./scripts/test.sh

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

    - name: Verify release artifacts
      run: ./scripts/ci/verify.sh

    - name: Upload release assets checksum
      uses: actions/upload-artifact@v4
      with:
        name: checksums
        path: dist/checksums.txt
        retention-days: 90

  publish-homebrew:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout homebrew tap
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/homebrew-nophr
        token: ${{ secrets.TAP_GITHUB_TOKEN }}

    - name: Update formula
      run: |
        # GoReleaser already updated the formula
        # This job is for any additional homebrew-specific tasks
        echo "Formula updated by GoReleaser"
